name: Create Release
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-*'

# Set permissions of the GITHUB_TOKEN to allow creation of a new release
permissions:
  contents: write

jobs:
  update-version:
      runs-on: ubuntu-latest
      concurrency: ci-${{github.ref}}
      steps:
        - name: Checkout
          uses: actions/checkout@v6

        - name: Update version number
          run: |
            sed -i -e 's/^version = ".*"$/version = "${{ github.ref_name }}"/g' ./Cargo.toml
            sed -i -e 's/^version = "v\(.*\)"$/version = "\1"/g' ./Cargo.toml

        - name: Update wasmfenbein3d version in Cargo.lock
          run: |
            perl -0777pe 's/name = "wasmfenbein3d"\nversion = ".*"/name = "wasmfenbein3d"\nversion = "${{ github.ref_name }}"/' ./Cargo.lock > ./temp.txt
            perl -0777pe 's/name = "wasmfenbein3d"\nversion = "v(.*)"/name = "wasmfenbein3d"\nversion = "\1"/' ./temp.txt > ./Cargo.lock
            rm temp.txt

        - name: Commit new version number
          run: |
            git config --global user.name 'Github Actions'
            git config --global user.email 'github@example.com'
            git commit -am "chore(version): Update package version to ${{ github.ref_name }}"
            git push origin HEAD:main

  build-release:
      needs: update-version
      runs-on: ubuntu-latest
      concurrency: ci-${{github.ref}}
      steps:
        - name: Rust setup
          uses: actions-rust-lang/setup-rust-toolchain@v1
          with:
            target: wasm32-unknown-unknown

        - name: Trunk setup
          run: cargo install --locked trunk

        - name: Build
          run: trunk build --release

        - name: Create release archives
          run: |
            # Create tarball for Unix systems
            tar -czvf wasmfenbein3d-${{ github.ref_name }}.tar.gz -C dist .

        - name: Create GitHub Release
          uses: softprops/action-gh-release@v3
          with:
            name: Release ${{ github.ref_name }}
            body: "TODO: Manually write release notes"
            draft: false
            prerelease: ${{ contains(github.ref_name, '-') }}  # Pre-release if tag has hyphen
            files: |
              wasmfenbein3d-*.tar.gz
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}